backend: mongodb # mongodb | redis | clickhouse
mongo:
  uri: mongodb://localhost:27017
  database: polydb
redis:
  uri: redis://localhost:6379/0
  database: polydb
clickhouse:
  host: localhost
  port: 9000
  database: default